### ISSUE TITLE
400 Client Error: Bad Request for URL

### ISSUE THREAD

**Issue by qbinary** [TrainDoctor/PZModScraper#2]
```python
Traceback (most recent call last):
  File "/home/pzserver/PZModScraper/getcollection.py", line 60, in request_ugc
    return api.call(method_path='ISteamRemoteStorage.GetPublishedFileDetails',\
  File "/home/pzserver/.local/lib/python3.10/site-packages/steam/webapi.py", line 167, in call
    return getattr(getattr(self, interface), method)(**kwargs)
  File "/home/pzserver/.local/lib/python3.10/site-packages/steam/webapi.py", line 327, in __call__
    return webapi_request(
  File "/home/pzserver/.local/lib/python3.10/site-packages/steam/webapi.py", line 431, in webapi_request
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pzserver/PZModScraper/getcollection.py", line 272, in <module>
    modjson = request_ugc(len(wscollection),\
  File "/home/pzserver/PZModScraper/getcollection.py", line 63, in request_ugc
    print("HTTP Error encountered, exiting." + e.with_traceback())
TypeError: BaseException.with_traceback() takes exactly one argument (0 given)
```

* Command used: `python3 getcollection.py default`
* I supplied a collection id
* I supplied an API key
* I ran the script from the folder it is in

**Comment by TrainDoctor** [comment]
Looks like the URL for the API call needs to be changed. I might get time to take a look at this soon but I'm not sure.

**Comment by TrainDoctor** [comment]
Have never been able to repro. Closing.
